name: Tag Differ

on:
  - pull_request

jobs:
  tag-differ:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: invertase/quickstart-tag-differ@feat/v1
        with:
          base-ref: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
