name: Tag Differ

on:
  - pull_request

jobs:
  tag-differ:
    runs-on: ubuntu-latest
    steps:
      - uses: invertase/quickstart-tag-differ@feat/v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repo-url: https://github.com/firebase/quickstart-android.git
