name: Android CI

on:
  - pull_request
  - push

jobs:
  tag-differ:
    runs-on: ubuntu-latest
    steps:
      - uses: invertase/quickstart-tag-differ@feat/v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
