name: Tag Differ

on:
  - pull_request

permissions:
  pull-requests: write

jobs:
  tag-differ:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: invertase/quickstart-tag-differ@feat/v1
        with:
          base-ref: master
          github-token: ${{ github.token }}
          included-change-types: file_path,code_contents
